# see https://www.lewagon.com/blog/setup-meta-tags-rails

meta_title: "Ventilator Alarm Sound Monitor"
meta_product_name: "Open Source Ventilator Alarm Sound Monitor"
meta_description: ""
meta_image: "cover.png" # should exist in `app/assets/images/`
